{
 "title": "Reco-app Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"reco-app\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"172.16.238.10:8000\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"reco-app\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Request per 5 minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[5m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Errors per 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status!=\"2xx\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per 5 minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"reco-app\"}[5m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[5m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50 (2 min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[2m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90 (5min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}