{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"reco-app\"}[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status!=\"2xx\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"reco-app\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"reco-app\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"reco-app\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}