global:
  scrape_interval: 1m
  evaluation_interval: 15s
  external_labels:
    monitor: "reco-app"

rule_files:

scrape_configs:
  # - job_name: "prometheus"

  #   static_configs:
  #     - targets: ["localhost:9090"]

  - job_name: "reco-app"
    dns_sd_configs:
      - names: ["reco-app"]
        port: 8000
        type: A
        refresh_interval: 30s
